<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="robotic_reel_mower">

  <!-- Xacro Properties for Dimensions -->
  <xacro:property name="chassis_length" value="0.19" />
  <xacro:property name="chassis_width" value="0.44" />
  <xacro:property name="chassis_height" value="0.22" />
  <xacro:property name="chassis_mass" value="2.27" />

  <xacro:property name="counterweight_length" value="0.21" />
  <xacro:property name="counterweight_width" value="0.13" />
  <xacro:property name="counterweight_height" value="0.13" />
  <xacro:property name="counterweight_mass" value="9.07" />

  <xacro:property name="wheel_radius" value="0.0975" />
  <xacro:property name="wheel_width" value="0.036" />
  <xacro:property name="wheel_mass" value="1.81" />
  <xacro:property name="wheel_separation" value="0.46" />

  <xacro:property name="front_roller_radius" value="0.04445" />
  <xacro:property name="front_roller_width" value="0.33" />
  <xacro:property name="front_roller_mass" value="0.45" />

  <xacro:property name="reel_radius" value="0.0875" />
  <xacro:property name="reel_width" value="0.47" />
  <xacro:property name="reel_mass" value="11.34" />

  <xacro:property name="reel_motor_mass" value="1.0" />

  <!-- IMU sensor position -->
  <xacro:property name="imu_x" value="0.0775" />
  <xacro:property name="imu_y" value="0.0875" />
  <xacro:property name="imu_z" value="0.169" />

  <!-- GPS sensor position -->
  <xacro:property name="gps_x" value="0.0" />
  <xacro:property name="gps_y" value="0.21415" />
  <xacro:property name="gps_z" value="0.253" />

  <!-- Base Link (using exactly the structure Gazebo expects) -->
  <link name="base_link">
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="${chassis_mass}"/>
      <inertia ixx="${chassis_mass * (chassis_width*chassis_width + chassis_height*chassis_height) / 12}" 
               ixy="0.0" ixz="0.0" 
               iyy="${chassis_mass * (chassis_length*chassis_length + chassis_height*chassis_height) / 12}" 
               iyz="0.0" 
               izz="${chassis_mass * (chassis_length*chassis_length + chassis_width*chassis_width) / 12}"/>
    </inertial>
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
      </geometry>
      <material name="blue">
        <color rgba="0.0 0.0 1.0 1.0"/>
      </material>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
      </geometry>
    </collision>
  </link>

  <!-- Counterweight Link -->
  <link name="counterweight">
    <visual>
      <geometry>
        <box size="${counterweight_length} ${counterweight_width} ${counterweight_height}"/>
      </geometry>
      <material name="gray">
        <color rgba="0.5 0.5 0.5 1.0"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <box size="${counterweight_length} ${counterweight_width} ${counterweight_height}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="${counterweight_mass}"/>
      <inertia ixx="${counterweight_mass * (counterweight_width*counterweight_width + counterweight_height*counterweight_height) / 12}" 
               ixy="0.0" ixz="0.0" 
               iyy="${counterweight_mass * (counterweight_length*counterweight_length + counterweight_height*counterweight_height) / 12}" 
               iyz="0.0" 
               izz="${counterweight_mass * (counterweight_length*counterweight_length + counterweight_width*counterweight_width) / 12}"/>
    </inertial>
  </link>

  <!-- Counterweight Joint -->
  <joint name="chassis_to_counterweight" type="fixed">
    <parent link="base_link"/>
    <child link="counterweight"/>
    <origin xyz="-${(chassis_length + counterweight_length)/2} 0.0 -${(chassis_height - counterweight_height)/2}" rpy="0 0 0"/>
  </joint>

  <!-- Right Wheel Link -->
  <link name="right_wheel">
    <visual>
      <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
      <material name="black">
        <color rgba="0.0 0.0 0.0 1.0"/>
      </material>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="${wheel_mass}"/>
      <inertia ixx="${wheel_mass * (3*wheel_radius*wheel_radius + wheel_width*wheel_width) / 12}" 
               ixy="0.0" ixz="0.0" 
               iyy="${wheel_mass * wheel_radius*wheel_radius / 2}" 
               iyz="0.0" 
               izz="${wheel_mass * (3*wheel_radius*wheel_radius + wheel_width*wheel_width) / 12}"/>
    </inertial>
  </link>

  <!-- Right Wheel Joint -->
  <joint name="right_wheel_joint" type="continuous">
    <parent link="base_link"/>
    <child link="right_wheel"/>
    <origin xyz="0.0 -${wheel_separation/2} -${chassis_height/2}" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
  </joint>

  <!-- Left Wheel Link -->
  <link name="left_wheel">
    <visual>
      <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
      <material name="black">
        <color rgba="0.0 0.0 0.0 1.0"/>
      </material>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="${wheel_mass}"/>
      <inertia ixx="${wheel_mass * (3*wheel_radius*wheel_radius + wheel_width*wheel_width) / 12}" 
               ixy="0.0" ixz="0.0" 
               iyy="${wheel_mass * wheel_radius*wheel_radius / 2}" 
               iyz="0.0" 
               izz="${wheel_mass * (3*wheel_radius*wheel_radius + wheel_width*wheel_width) / 12}"/>
    </inertial>
  </link>

  <!-- Left Wheel Joint -->
  <joint name="left_wheel_joint" type="continuous">
    <parent link="base_link"/>
    <child link="left_wheel"/>
    <origin xyz="0.0 ${wheel_separation/2} -${chassis_height/2}" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
  </joint>

  <!-- Front Roller Link -->
  <link name="front_roller">
    <visual>
      <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
      <geometry>
        <cylinder radius="${front_roller_radius}" length="${front_roller_width}"/>
      </geometry>
      <material name="white">
        <color rgba="1.0 1.0 1.0 1.0"/>
      </material>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
      <geometry>
        <cylinder radius="${front_roller_radius}" length="${front_roller_width}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="${front_roller_mass}"/>
      <inertia ixx="${front_roller_mass * (3*front_roller_radius*front_roller_radius + front_roller_width*front_roller_width) / 12}" 
               ixy="0.0" ixz="0.0" 
               iyy="${front_roller_mass * front_roller_radius*front_roller_radius / 2}" 
               iyz="0.0" 
               izz="${front_roller_mass * (3*front_roller_radius*front_roller_radius + front_roller_width*front_roller_width) / 12}"/>
    </inertial>
  </link>

  <!-- Front Roller Joint -->
  <joint name="front_roller_joint" type="continuous">
    <parent link="base_link"/>
    <child link="front_roller"/>
    <origin xyz="0.48 0.0 -${chassis_height/2 + front_roller_radius}" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
  </joint>

  <!-- Reel Link -->
  <link name="reel">
    <visual>
      <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
      <geometry>
        <cylinder radius="${reel_radius}" length="${reel_width}"/>
      </geometry>
      <material name="green">
        <color rgba="0.0 1.0 0.0 1.0"/>
      </material>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
      <geometry>
        <cylinder radius="${reel_radius}" length="${reel_width}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="${reel_mass}"/>
      <inertia ixx="${reel_mass * (3*reel_radius*reel_radius + reel_width*reel_width) / 12}" 
               ixy="0.0" ixz="0.0" 
               iyy="${reel_mass * reel_radius*reel_radius / 2}" 
               iyz="0.0" 
               izz="${reel_mass * (3*reel_radius*reel_radius + reel_width*reel_width) / 12}"/>
    </inertial>
  </link>

  <!-- Reel Joint -->
  <joint name="reel_joint" type="continuous">
    <parent link="base_link"/>
    <child link="reel"/>
    <origin xyz="0.30 0.0 -${chassis_height/2 - 0.02}" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
  </joint>

  <!-- Reel Motor Link -->
  <link name="reel_motor">
    <visual>
      <geometry>
        <box size="0.05 0.05 0.05"/>
      </geometry>
      <material name="red">
        <color rgba="1.0 0.0 0.0 1.0"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <box size="0.05 0.05 0.05"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="${reel_motor_mass}"/>
      <inertia ixx="${reel_motor_mass * (0.05*0.05 + 0.05*0.05) / 12}" 
               ixy="0.0" ixz="0.0" 
               iyy="${reel_motor_mass * (0.05*0.05 + 0.05*0.05) / 12}" 
               iyz="0.0" 
               izz="${reel_motor_mass * (0.05*0.05 + 0.05*0.05) / 12}"/>
    </inertial>
  </link>

  <!-- Reel Motor Joint -->
  <joint name="chassis_to_reel_motor" type="fixed">
    <parent link="base_link"/>
    <child link="reel_motor"/>
    <origin xyz="0.125 0.11 0.04" rpy="0 0 0"/>
  </joint>

  <!-- IMU Sensor Link -->
  <link name="imu_link">
    <visual>
      <geometry>
        <box size="0.02 0.02 0.01"/>
      </geometry>
      <material name="purple">
        <color rgba="0.5 0.0 0.5 1.0"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <box size="0.02 0.02 0.01"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="0.01"/>
      <inertia ixx="0.000001" ixy="0.0" ixz="0.0" iyy="0.000001" iyz="0.0" izz="0.000001"/>
    </inertial>
  </link>

  <!-- IMU Sensor Joint -->
  <joint name="base_to_imu" type="fixed">
    <parent link="base_link"/>
    <child link="imu_link"/>
    <origin xyz="${imu_x} ${imu_y} ${imu_z - wheel_radius - chassis_height/2}" rpy="0 0 0"/>
  </joint>

  <!-- GPS Sensor Link -->
  <link name="gps_link">
    <visual>
      <geometry>
        <box size="0.03 0.03 0.01"/>
      </geometry>
      <material name="orange">
        <color rgba="1.0 0.5 0.0 1.0"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <box size="0.03 0.03 0.01"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="0.01"/>
      <inertia ixx="0.000001" ixy="0.0" ixz="0.0" iyy="0.000001" iyz="0.0" izz="0.000001"/>
    </inertial>
  </link>

  <!-- GPS Sensor Joint -->
  <joint name="base_to_gps" type="fixed">
    <parent link="base_link"/>
    <child link="gps_link"/>
    <origin xyz="${gps_x} ${gps_y} ${gps_z - wheel_radius - chassis_height/2}" rpy="0 0 0"/>
  </joint>

</robot>
